# Generated by Django 5.2.8 on 2025-11-10 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre OT')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('dateOt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creacion')),
                ('clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.client', verbose_name='Asignada')),
                ('ctg', models.ManyToManyField(to='ordenes.category', verbose_name='Categorias')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
